kind: pipeline
type: kubernetes
name: hulu-project


steps:
- name: docker-build
  image: plugins/docker
  settings:
    repo: repo.internal.hafuhafu.cn/hulu0811/huluproject-api
    registry: repo.internal.hafuhafu.cn
    target: build
    cache_from: repo.internal.hafuhafu.cn/hulu0811/huluproject-api:build
    tags:
      - build


- name: docker-final
  image: plugins/docker
  settings:
    repo: repo.internal.hafuhafu.cn/hulu0811/huluproject-api
    registry: repo.internal.hafuhafu.cn
    cache_from: 
      - repo.internal.hafuhafu.cn/hulu0811/huluproject-api:build
      - repo.internal.hafuhafu.cn/hulu0811/huluproject-api:latest
    tags:
      - latest
      - ${DRONE_COMMIT}

- name: dron8s-api
  image: bh90210/dron8s:latest
  settings:
    yaml: ./deploy.yaml
    image_tag: ${DRONE_COMMIT}
    kubeconfig:
        from_secret: kubeconfig
