kind: pipeline
type: kubernetes
name: hulu-project

steps:

- name: docker-api
  image: plugins/docker
  volumes: 
  - name: docker
    path: /var/run/docker.sock
  settings:
    mirror: https://jnyis2wm.mirror.aliyuncs.com
    build_args:
      - network=host
    username:
      from_secret: username
    password:
      from_secret: password
    repo: registry-vpc.cn-shanghai.aliyuncs.com/hulu0811/huluproject-api
    registry: registry-vpc.cn-shanghai.aliyuncs.com
    tags:
      - latest
      - ${DRONE_COMMIT}

- name: dron8s-api
  image: bh90210/dron8s:latest
  settings:
    yaml: ./deploy.yaml
    # variables. Must be lowercase, Usage: {{.image_tag}}
    image_tag: ${DRONE_COMMIT}
    kubeconfig:
        from_secret: kubeconfig

volumes: 
  - name: docker
    host:
      path: /var/run/docker.sock


---
kind: secret
name: username
get:
  path: docker-secret
  name: DOCKER_USERNAME

---
kind: secret
name: password
get:
  path: docker-secret
  name: DOCKER_PASSWORD

---
kind: secret
name: kubeconfig
get:
  path: kubeconfig
  name: KUBECONFIG